# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
  os: ubuntu-20.04
  apt_packages:
    - libtag1-dev
  tools:
    python: "3.9"

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: true

python:
  install:
    - requirements: requirements_dev.txt
