#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
tagrenamer - Mass music collection renamer

@description
  Tagrenamer lets you mass-rename music collection trees provided each file
  has valid metadata tags. It preserves non-music files by putting them into
  the '__LEFTOVERS' folder. You can use --dry-run to simulate or the --shell
  option to generate a list of commands you can first review.

@author
  Niels van Mourik <niels@nielsvm.org>
"""


import sys
from lib.output import runtime_error

if __name__ == "__main__":
    try:

        # Import the core libraries and handle import errors:
        try:
            from lib.output import Output
            from lib.settings import Settings
            from lib.collection import Collection
        except ImportError as e:
            runtime_error("%s\n\n"
                          "Check if these Python packages are installed:\n"
                          "- transliterate\n"
                          "- taglib (pytaglib)" % e)

        # Construct the settings and output objects:
        settings = Settings()
        output = Output()
        output.set_debuglevel(settings.debuglevel)
        output.set_quiet(settings.quiet)
        output.log(context = __name__)

        # Dispatch application control to the collection processor.
        collection = Collection(output, settings)
        collection.process()
    except RuntimeError as e:
        print(e)
        sys.exit(1)
    except KeyboardInterrupt:
        print("Quitting...")
        sys.exit(-1)
